include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
