name: my_fiskal_app
description: Фискальный менеджер - управление чеками, терминалами и пользователями.
publish_to: 'none' # Этот проект не публикуется в pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    # Добавьте сюда другие изображения, если они есть
